# Generated by Django 6.0.5 on 2026-06-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='Без названия', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
