# Generated by Django 6.0.4 on 2026-06-13 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss_app', '0002_question_title_alter_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='discuss_app.question'),
        ),
    ]
